### PR TITLE
allow spaces before '-' in yaml-scalar-context-re

### PR DESCRIPTION
**Pull request by antalk2**
# to recognize (indent and color) lala lines below

- aa: dada
  bb:
  - cc: |
    lala
    lala

### CODE REVIEW

**Comment by wasamasa** [comment]
Before I merge this, I'd like to have a previously broken code block example (instead of plain text), a description of the broken behaviour and a description of the fixed behaviour.  Ideally in sufficient detail so that I could write a regression test ensuring I never run into this bug again.

**Comment by wasamasa** [comment]
Also, why does this pull request touch a different variable than https://github.com/antalk2/yaml-mode/commit/e2e3a257c7239f0570f8fde816a7d1320afa1daf?

**Comment by antalk2** [comment]
> Also, why does this pull request touch a different variable than antalk2@e2e3a25?

It was a mistake, I sent the change preceding the one you asked for. I think it does solve a problem
though. Shall I create a bug report for it?

At https://github.com/antalk2/yaml-mode/commit/e2e3a257c7239f0570f8fde816a7d1320afa1daf
github does not offer to create a pull request. Probably because it is not directly based on the
yoshiki branch. I guess I have to rebase it somehow. Is there a simpler way?

> Before I merge this, I'd like to have a previously broken code block example (instead of plain text), 
> a description of the broken behaviour and a description of the fixed behaviour. Ideally in sufficient
> detail so that I could write a regression test ensuring I never run into this bug again.

Under the `broken code block example` you mean a YAML file in a role like
for example https://github.com/josteink/csharp-mode/blob/master/test-files/imenu-comment-test.cs ,
and description sufficient for you to write something like
https://github.com/josteink/csharp-mode/blob/master/csharp-mode-tests.el ?

**Comment by wasamasa** [comment]
> It was a mistake, I sent the change preceding the one you asked for. I think it does solve a problem though. Shall I create a bug report for it?

Yes.  Please describe what exactly it is doing, demonstrate the bug and how it's fixed by the patch.

> Is there a simpler way?

Well, given that you have cloned this repository before and made a branch for creating a pull request, you could just create a branch based on master, commit the change, push and open another pull request for it.

> Under the broken code block example you mean a YAML file in a role like
for example https://github.com/josteink/csharp-mode/blob/master/test-files/imenu-comment-test.cs ,
and description sufficient for you to write something like
https://github.com/josteink/csharp-mode/blob/master/csharp-mode-tests.el ?

Yes.

**Comment by antalk2** [comment]
Intended to solve
https://github.com/yoshiki/yaml-mode/issues/35

**Comment by wasamasa** [comment]
Thank you.

**Pull request merged**
