### PR TITLE
fix: #96 highlight error with inline comments

### PR DESCRIPTION
**Pull request by liuyinz**
@wasamasa please check it

### CODE REVIEW

**Comment by liuyinz** [comment]
Is there any maintainer for the project now ? Several months have passed..

**Comment by syohex** [comment]
I'm afraid that I don't have any permissions of this repository

**Comment by liuyinz** [comment]
Sorry, I make a mistake here.

**Comment by yoshiki** [comment]
Thankfully, @wasamasa is currently doing most of the maintenance.
I have not been able to get involved in most of it.

@syohex 
If you are interested and able to collaborate, would you join us as one of the maintainers?

**Comment by syohex** [comment]
@yoshiki Thanks, sure. I would check issues when I have free time. Please feel free to give me repository permissions.

**Comment by wasamasa** [comment]
I've been pretty busy the last few months, sorry about that. Doesn't look like it will get better soon. Therefore, I do welcome @syohex aboard. That being said, there's a few things to be kept in mind:

- Non-trivial contributions require copyright assignment to not impede the GNU ELPA ticket (see #44)
- Non-trivial changes require a YAML test file that allows easily checking whether the issue has indeed been fixed and whether future changes break it again
- There's a release process and the Debian package depends on it being done correctly (see https://github.com/yoshiki/yaml-mode/commit/fc5e1c58f94472944c4aa838f00f6adcac6fa992 for an example commit)

@liuyinz The regex could be simplified by changing to `\\b` because what you're really trying to do is match a word boundary, not end of line or spaces.

**Comment by yoshiki** [comment]
@syohex 
Thank you for your cooperation.
I just invited you to the maintainer for this repository. Please check it.
Of course, it's ok to check issues when you have time. 😄 

@wasamasa 
Thanks again for all your support.
Please keep up the good work with the new maintainer @syohex.

**Comment by syohex** [comment]
> Non-trivial contributions require copyright assignment to not impede the GNU ELPA ticket (see https://github.com/yoshiki/yaml-mode/issues/44)

I have already sent copyright assignment to GNU

**Comment by syohex** [comment]
@liuyinz , @wasamasa  I sent PR #101 which includes this change. Please check it.

**Comment by liuyinz** [comment]
#101 fixed. @syohex, I'll closed this pr

**Pull request closed without merging**
