### PR TITLE
Speed up syntax-propertize-function in files with large JSON strings

### PR DESCRIPTION
**Pull request by dgutov**

### CODE REVIEW

**Comment by wasamasa** [comment]
Thanks, the code looks good, the function doesn't seem to work consistently yet though. Here's how it looks right after opening a buffer, compared to after changing a character in the key, then adding it back.




Could this be some wonky font-lock customization in the major mode preventing jit-lock from fontifying the entire region?

**Comment by dgutov** [comment]
It... seems to do with syntax-ppss cache, actually. Though I don't understand why this doesn't affect subsequent parses.

**Comment by dgutov** [comment]
Good catch, thank you.

**Comment by dgutov** [comment]
Should be fixed now.

**Comment by wasamasa** [comment]
Thanks, that did indeed fix it.

**Pull request merged**
